server {
    listen 80;
    
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    location /media/ {
        root /usr/share/nginx/html;
        expires 30d;
        add_header Access-Control-Allow-Origin *;
    }

    location /socket.io {
        proxy_pass http://game-app:5000/socket.io;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Увеличенные таймауты для стабильности через облачный доступ Keenetic
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;

        # Отключаем кэширование для WebSocket
        proxy_cache_bypass $http_upgrade;
    }

    location / {
        proxy_pass http://game-app:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


}

server {
    listen 443 ssl;
    # Если заходите по IP, укажите его здесь, или оставьте _
    server_name _;

    # Подключаем наши самодельные сертификаты
    ssl_certificate /etc/nginx/ssl/selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

    # Оптимизация SSL (необязательно, но полезно)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # === OPENCLAW ===
    # Лучше вешать на корень или поддомен, но если хотите /claw/:
    location / {
        # 172.17.0.1 — это стандартный IP хоста изнутри контейнера Docker.
        # Мы стучимся на внешний порт 18789, который открыл скрипт OpenClaw.
        proxy_pass http://172.17.0.1:18789;
        proxy_set_header Origin "https://localhost:18789";
        # Магия WebSockets (критично для OpenClaw)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        # Передаем реальные заголовки
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https; # Говорим OpenClaw, что мы сидим через HTTPS

        # Тайм-ауты, чтобы не разрывало соединение
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}
